## https://home-assistant.io/components/frontend/
## https://home-assistant.io/developers/frontend_creating_custom_ui/

javascript_version: es5

extra_html_url:    
  - /local/custom_ui/state-card-custom-ui.html
  - /local/custom_ui/state-card-tiles.html
  #- /local/custom_ui/state-card-mini-media-player.html
  #- /local/custom_ui/state-card-text.html

extra_html_url_es5:
  - /local/custom_ui/state-card-custom-ui-es5.html
  - /local/custom_ui/state-card-tiles_es5.html
  #- /local/custom_ui/state-card-mini-media-player_es5.html
  #- /local/custom_ui/state-card-text.html

themes: !include frontend_themes.yaml
